name: Solve Today's Wordle

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  solve_wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start X Virtual Framebuffer (Xvfb)
        run: |
          if ! pgrep -x "Xvfb" > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y xvfb
            sudo Xvfb :99 -ac & 
          fi
          export DISPLAY=:99

      - name: Run Wordle solver
        run: python main.py
        env:
          DISPLAY: :99

      - name: Commit and push updates
        run: |
          git config --global user.name 'Wordle Solver'
          git add wordle_solves.csv last_saved_date.txt
          git diff --quiet || git commit -m "Update wordle_solves"
          git push
