name: Solve Today's Wordle

on:
  schedule:
    - cron: '*/10 * * * *'  #  1 * 1 * *

jobs:
  solve_wordle:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Cache Python dependencies for faster runs
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install required Python packages 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install and start Xvfb for display simulation
      - name: Start X Virtual Framebuffer (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          # Start Xvfb in the background on display :99
          sudo Xvfb :99 -ac &
          export DISPLAY=:99

      # Step 6: Run the Python script (main.py)
      - name: Run Wordle solver
        run: python main.py
        env:
          DISPLAY: :99  # Ensure DISPLAY variable is set for the script

      # Step 7: Commit and push updated wordle_solves.csv and last_saved_date.txt
      - name: Commit and push updates
        run: |
          git config --global user.name 'Wordle Solver'
          git add wordle_solves.csv last_saved_date.txt
          git commit -m "Update wordle_solves"
          git push
